apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: lbmjm-ambulance-webapi-mongodb-init
    files:
      - params/init-db.js
  - name: lbmjm-ambulance-webapi-config
    literals:
      - database=lbmjm-ambulance
      - collection=ambulance
patches:
 - path: patches/webapi.deployment.yaml
   target:
     group: apps
     version: v1
     kind: Deployment
     name: lbmjm-ambulance-webapi