/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: test@test.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

type SchedulesAPI interface {

	// internal registration of api routes
	addRoutes(routerGroup *gin.RouterGroup)

	// CreateSchedule - Saves new entry into schedule list
	CreateSchedule(ctx *gin.Context)

	// DeleteSchedule - Deletes specific schedule entry
	DeleteSchedule(ctx *gin.Context)

	// GetSchedule - Provides the ambulance schedule
	GetSchedule(ctx *gin.Context)

	// UpdateSchedule - Updates specific schedule entry
	UpdateSchedule(ctx *gin.Context)
}

// partial implementation of SchedulesAPI - all functions must be implemented in add on files
type implSchedulesAPI struct {
}

func newSchedulesAPI() SchedulesAPI {
	return &implSchedulesAPI{}
}

func (this *implSchedulesAPI) addRoutes(routerGroup *gin.RouterGroup) {
	routerGroup.Handle(http.MethodPost, "/schedules/:ambulanceId/entries", this.CreateSchedule)
	routerGroup.Handle(http.MethodDelete, "/schedules/:ambulanceId/entries", this.DeleteSchedule)
	routerGroup.Handle(http.MethodGet, "/schedules/:ambulanceId/entries", this.GetSchedule)
	routerGroup.Handle(http.MethodPut, "/schedules/:ambulanceId/entries", this.UpdateSchedule)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateSchedule - Saves new entry into schedule list
// func (this *implSchedulesAPI) CreateSchedule(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // DeleteSchedule - Deletes specific schedule entry
// func (this *implSchedulesAPI) DeleteSchedule(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetSchedule - Provides the ambulance schedule
// func (this *implSchedulesAPI) GetSchedule(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // UpdateSchedule - Updates specific schedule entry
// func (this *implSchedulesAPI) UpdateSchedule(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
