/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: test@test.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"time"
)

type Schedule struct {

	// Unique id of the entry in this waiting list
	Id string `json:"id"`

	// Unique identifier of the patient known to Web-In-Cloud system
	PatientId string `json:"patientId"`

	RoomId string `json:"roomId"`

	Note string `json:"note"`

	// Timestamp since when the patient entered the waiting list
	Start time.Time `json:"start"`

	// Estimated time of entering ambulance. Ignored on post.
	End time.Time `json:"end"`
}
